apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-code-config
  namespace: pradeep-av
  labels:
    app.kubernetes.io/instance: code-server
    app.kubernetes.io/name: code-server
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
  namespace: pradeep-av
  labels:
    app.kubernetes.io/instance: code-server
    app.kubernetes.io/name: code-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: code-server
      app.kubernetes.io/name: code-server
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: code-server
        app.kubernetes.io/name: code-server
    spec:
      containers:
      - image: ghcr.io/avp-cloud/code-server:v2.2.0
        imagePullPolicy: IfNotPresent
        name: code-server
        env:
        - name: PASSWORD
          value: CHANGE_ME
        ports:
        - containerPort: 8443
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /config
          name: code-config
      volumes:
      - name: code-config
        persistentVolumeClaim:
          claimName: code-server-code-config
---
apiVersion: v1
kind: Service
metadata:
  name: code-server
  namespace: pradeep-av
  labels:
    app.kubernetes.io/instance: code-server
    app.kubernetes.io/name: code-server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: code-server
    app.kubernetes.io/name: code-server
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
